baseURL = 'https://pabloquiros.xyz/'
languageCode = 'es'
title = 'Pablo Quirós'

enableRobotsTXT = true

defaultContentLanguage = 'es'
defaultContentLanguageInSubdir = false

[languages]
  [languages.es]
    languageName = 'Español'
    languageCode = 'es'
    weight = 1
    contentDir = 'content/es'
    [languages.es.permalinks]
      journal_entries = '/bitacora/:slugorfilename/'
    [languages.es.permalinks.taxonomy]
      tags = '/bitacora/tags/'
      book_tags = '/libros/tags/'
      movie_tags = '/peliculas/tags/'
    [languages.es.permalinks.term]
      tags = '/bitacora/tags/:slug/'
      book_tags = '/libros/tags/:slug/'
      movie_tags = '/peliculas/tags/:slug/'
  [languages.en]
    languageName = 'English'
    languageCode = 'en'
    weight = 2
    contentDir = 'content/en'
    [languages.en.permalinks]
      journal_entries = '/journal/:slugorfilename/'
    [languages.en.permalinks.taxonomy]
      tags = '/journal/tags/'
      book_tags = '/books/tags/'
      movie_tags = '/movies/tags/'
    [languages.en.permalinks.term]
      tags = '/journal/tags/:slug/'
      book_tags = '/books/tags/:slug/'
      movie_tags = '/movies/tags/:slug/'

[taxonomies]
  tag = 'tags'
  book_tag = 'book_tags'
  movie_tag = 'movie_tags'

[markup.goldmark.renderer]
# Required for trusted raw HTML used in Markdown content (details/audio/div layout blocks).
unsafe = true

[markup.goldmark.parser.attribute]
block = true
title = true
